ScoreSystem/Controllers/CuponsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ScoreSystem.Entidades;
using ScoreSystem.Models;

namespace ScoreSystem.Controllers
{
    //[Authorize(Roles ="Administrador")]
    public class CuponsController : Controller
    {
        private Contexto db;
        public CuponsController(Contexto contexto)
        {

            db = contexto;
        }

        [Authorize(Roles ="Administrador")]
        public IActionResult Lista()
        {
            return View(db.CUPOM.ToList());
        }

        [Authorize(Roles ="Administrador")]
        public IActionResult Cadastro()
        {
            CuponsViewModel model = new CuponsViewModel();
            return View(model);
        }

        public IActionResult Visualizar(int id)
        {
            var cupom = db.CUPOM.Find(id);

            if (cupom != null)
            {
                return View(cupom);

            }
            else
            {
                return NotFound();
            }

        }

        [Authorize(Roles ="Administrador")]
        public ActionResult Excluir(int id)
        {
            Cupom item = db.CUPOM.Find(id);
            if (item != null)
            {
                db.CUPOM.Remove(item);
                db.SaveChanges();

                TempData["Sucesso"] = "Cupom excluido com sucesso";

            }

            return RedirectToAction("Lista");
        }
        [Authorize(Roles ="Administrador")]
        public IActionResult Editar(int id)
        {
            Cupom item = db.CUPOM.Find(id);
            if (item != null)
            {
                return View(item);
            }
            else
            {
                return RedirectToAction("Lista");
            }

        }

        [Authorize(Roles ="Administrador")]
        public IActionResult SalvarDados(Cupom dados)
        {
            
            if(dados.CODIGO > 0)
            {
                db.CUPOM.Update(dados);
                db.SaveChanges();
                TempData["Sucesso"] = "Cupom editado com sucesso!";

            }
            else
            {
                if (dados.DT_VENCIMENTO < DateTime.Now)
                {
                    dados.DT_VENCIMENTO = DateTime.Now;
                }
                db.CUPOM.Add(dados);
                db.SaveChanges();
            }
           
            return RedirectToAction("Lista");
        }

    }
}

ScoreSystem/Controllers/RecompensasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ScoreSystem.Models;
using ScoreSystem.Entidades;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace ScoreSystem.Controllers
{
    public class RecompensasController : Controller
    {
        private Contexto db;
        public RecompensasController(Contexto contexto)
        {

            db = contexto;
        }

        [Authorize(Roles = "Administrador")]

        public IActionResult Lista()
        {
            return View(db.RECOMPENSA.ToList());
        }

        [Authorize(Roles = "Administrador")]
        public IActionResult Cadastro()
        {
            RecompensasViewModel model = new RecompensasViewModel();
            return View(model);
        }
        public IActionResult Visualizar(int id)
        {
            var recompensa = db.RECOMPENSA.Find(id);

            if (recompensa != null)
            {
                return View(recompensa);

            }
            else
            {
                return NotFound();
            }

        }

        [Authorize(Roles = "Administrador")]
        public IActionResult Editar(int id)
        {
            Recompensas item = db.RECOMPENSA.Find(id);
            if (item != null)
            {
                return View(item);

            }
            else
            {
                return RedirectToAction("Lista");
            }


        }

        [Authorize(Roles = "Administrador")]
        public ActionResult Excluir(int id)
        {
            Recompensas item = db.RECOMPENSA.Find(id);
            if (item != null)
            {
                db.RECOMPENSA.Remove(item);
                db.SaveChanges();

                TempData["Sucesso"] = "Recompensa excluido com sucesso!";

            }

            return RedirectToAction("Lista");
        }

        [Authorize(Roles = "Administrador")]
        public IActionResult SalvarDados(Recompensas dados)
        {
            if (dados.CODIGO > 0)
            {
                db.RECOMPENSA.Update(dados);
                db.SaveChanges();
                TempData["Sucesso"] = "Recompensa editada com sucesso!";


            }
            else
            {
                if (dados.DT_VENCIMENTO < DateTime.Now)
                {
                    dados.DT_VENCIMENTO = DateTime.Now;
                }
                db.RECOMPENSA.Add(dados);
                db.SaveChanges();
            }

            return RedirectToAction("Lista");
        }
    }

}

ScoreSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ScoreSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ScoreSystem.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa&display=swap" rel="stylesheet">
</head>
<body>

    <div id="retanguloFundo" class="shadow"></div>

    <div class="conteudoPagina container">


        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4">
            <div class="col-md-3 mb-2 mb-md-0">
                <a href="/Home/Index" class="titulo d-inline-flex link-body-emphasis text-decoration-none text-light fw-bold h4 m-0">
                    Midas
                </a>
            </div>

            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">

                @if (User.IsInRole("Administrador"))
                {
                    <li class="nav-item">
                        <a class="nav-link px-2 text-light" asp-area="" asp-controller="Usuarios" asp-action="Lista">Usuarios</a>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link px-2 text-light" asp-area="" asp-controller="Cupons" asp-action="Lista">Cupons</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-2 text-light" asp-area="" asp-controller="Recompensas" asp-action="Lista">Recompensas</a>
                    </li>
                }
               


            </ul>

            <div class="col-md-3 text-end">
               
                <a type="button" class="btn btn-sm btn-outline-light me-2" asp-area="" asp-controller="Usuarios" asp-action="LogOff"><i class="bi bi-box-arrow-left"></i> Sair</a>
            </div>
        </header>


        <main role="main" class="pb-3">
            @RenderBody()

        </main>


        <footer class="border-top d-flex flex-wrap justify-content-between align-items-center py-3 px-2 my-4 border-top border-secondary">
            <div class="col-12 col-lg-6 d-flex align-items-center">
                <a href="/Home/Privacy"
                   class="titulo d-inline-flex link-body-emphasis text-decoration-none text-secondary fw-bold h5 m-0">
                    Midas
                </a>
                <span class="mb-3 mb-md-0  text-secondary">&ensp;| 2023 Projeto Integrador III - Fatec Tq</span>
            </div>
            <div class="col-12 col-lg-6 d-flex align-items-center justify-content-end gap-2  text-secondary">
                <a href="https://br.linkedin.com/"
                   class="mb-3 mb-md-0 text-body-secondary text-decoration-none text-secondary">
                    João Bernardelli
                </a>
                |
                <a href="https://br.linkedin.com/"
                   class="mb-3 mb-md-0 text-body-secondary text-decoration-none text-secondary">
                    Samuel Rosales
                </a>
                |
                <a href="https://br.linkedin.com/"
                   class="mb-3 mb-md-0 text-body-secondary text-decoration-none text-secondary">
                    Thais Oliveira
                </a>
            </div>
        </footer>
        
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/sweet-alert/sweetalert.min.js"></script>
    <script src="~/lib/jquery-mask/jquery.mask.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>